(self.AMP=self.AMP||[]).push({n:"amp-auto-lightbox",v:"2009252320001",f:(function(AMP,_){
'use strict';function n(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var h=b[c];if(h&&h.Math==Math)return}(function(){throw Error("Cannot find global object");})()}n(this);"function"===typeof Symbol&&Symbol("x");var p;function q(){var a,b;this.promise=new Promise(function(c,h){a=c;b=h});this.resolve=a;this.reject=b};function r(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(h){return c}};var t=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function u(a){return a?Array.prototype.slice.call(a):[]};var v=self.AMP_CONFIG||{},w=("string"==typeof v.cdnProxyRegex?new RegExp(v.cdnProxyRegex):v.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function x(a){if(self.document&&self.document.head&&(!self.location||!w.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}v.cdnUrl||x("runtime-host");v.geoApiUrl||x("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var y=self.__AMP_LOG;function z(){if(y.dev)return y.dev;throw Error("failed to call initLogConstructor");};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0});function A(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){z().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var h=0;h<c.length;h++)0!=c[h].length&&("-"==c[h][0]?a[c[h].substr(1)]=!1:a[c[h]]=!0);return a};function B(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function D(a,b){var c=E(a);c=F(c);return C(c,b)}function E(a){return a.nodeType?B((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a){a=E(a);return a.isSingleDoc()?a.win:a}function C(a,b){G(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function G(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function H(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}
function I(a){return a.closest?a.closest("a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):H(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,"a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):!1})}
function J(a){var b=a.tagName;4>b.length||b.lastIndexOf("AMP-",0);if(a.createdCallback)return Promise.resolve(a);a.__AMP_UPG_PRM||(b=new q,a.__AMP_UPG_PRM=b.promise,a.__AMP_UPG_RES=b.resolve);return a.__AMP_UPG_PRM};/nochunking=1/.test(self.location.hash);(function(){return p?p:p=Promise.resolve(void 0)})();var K={Article:!0,NewsArticle:!0,BlogPosting:!0,LiveBlogPosting:!0,DiscussionForumPosting:!0};function L(){}var M=/\s+([0-9]+)w(,|[\S\s]*$)/g;function N(a){return D(a,"mutator").mutateElement(a,function(){a.setAttribute("i-amphtml-auto-lightbox-visited","")})}function O(a){return J(a).then(function(a){return a.signals().whenSignal("load-end")})}
function P(a){return u(a.getRootNode().querySelectorAll('script[type="application/ld+json"]')).map(function(a){try{var b=JSON.parse(a.textContent)}catch(h){b=null}return(b||{})["@type"]}).filter(function(a){return a})}function Q(a){return P(a).some(function(a){return K[a]})}function R(a){function b(b){return!!a.getRootNode().querySelector(b)}return b('script[custom-element="amp-lightbox-gallery"]')&&b("[lightbox]:not([i-amphtml-auto-lightbox-visited])")}var S=0;
function T(a,b){return D(a,"mutator").mutateElement(b,function(){b.setAttribute("lightbox","i-amphtml-auto-lightbox-"+S++)}).then(function(){B(a.win,"extensions").installExtensionForDoc(a,"amp-lightbox-gallery");b.dispatchCustomEvent("amp-auto-lightbox:newly-set");return b})}
function U(a,b){b.map(function(b){return O(b).then(function(){var c;if(c=!b.signals().get("unload")){var e=b.querySelector("img");c=e.naturalWidth;var l=e.naturalHeight;var k=c/l;var d=-1;if(e=e.getAttribute("srcset"))for(var g;g=M.exec(e);)g=parseInt(g[1],10),g>d&&(d=g);l=d>c?{naturalWidth:d,naturalHeight:d/k}:{naturalWidth:c,naturalHeight:l};c=l.naturalWidth;l=l.naturalHeight;d=b.getLayoutBox();k=d.width;e=d.height;g=D(b,"viewport").getSize();d=g.width;g=g.height;k*=e;if(c=1.2<=c*l/k||c>d||l>g||
.25<=k/(d*g)){if(I(b))var f=!1;else{c=b.ownerDocument.defaultView;d=c.__AMP_TOP||(c.__AMP_TOP=c);l=c!=d;if(d.__AMP__EXPERIMENT_TOGGLES)f=d.__AMP__EXPERIMENT_TOGGLES;else{d.__AMP__EXPERIMENT_TOGGLES=Object.create(null);k=d.__AMP__EXPERIMENT_TOGGLES;if(d.AMP_CONFIG)for(f in d.AMP_CONFIG)e=d.AMP_CONFIG[f],"number"===typeof e&&0<=e&&1>=e&&(k[f]=Math.random()<e);if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-doc-opt-in"])&&0<d.AMP_CONFIG["allow-doc-opt-in"].length&&(f=d.AMP_CONFIG["allow-doc-opt-in"],
e=d.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(e=e.getAttribute("content").split(","),g=0;g<e.length;g++)-1!=f.indexOf(e[g])&&(k[e[g]]=!0);Object.assign(k,A(d));if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-url-opt-in"])&&0<d.AMP_CONFIG["allow-url-opt-in"].length){f=d.AMP_CONFIG["allow-url-opt-in"];e=d.location.originalHash||d.location.hash;d=Object.create(null);if(e)for(var m;m=t.exec(e);)g=r(m[1],m[1]),m=m[2]?r(m[2].replace(/\+/g," "),m[2]):"",d[g]=m;for(e=0;e<
f.length;e++)g=d["e-"+f[e]],"1"==g&&(k[f[e]]=!0),"0"==g&&(k[f[e]]=!1)}f=k}f=!!f["ampdoc-fie"];l&&!f?f=G(c,"action")?C(c,"action"):null:(f=E(b),f=F(f),f=G(f,"action")?C(f,"action"):null);f=!f.hasResolvableAction(b,"tap")}c=f}}if(c)return z().info("amp-auto-lightbox","apply",b),T(a,b)},L)})}
function V(a,b){if(R(a))var c=0;else c=(c=a.getRootNode().querySelector('meta[property="og:type"]'))?c.getAttribute("content"):void 0,c="article"==c||Q(a);c?(c=u((b||a.win.document).querySelectorAll("amp-img:not([lightbox]):not([i-amphtml-auto-lightbox-visited])")),c.forEach(N),U(a,c)):z().info("amp-auto-lightbox","disabled")}(function(a){var b=a.ampdoc;b.whenReady().then(function(){b.getRootNode().addEventListener("amp:dom-update",function(a){V(b,a.target)});V(b)})})(self.AMP);
})});

//# sourceMappingURL=amp-auto-lightbox-0.1.js.map
