(function(){'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},p={};try{p.__proto__=ca;n=p.a;break a}catch(a){}n=!1}k=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=k;function da(a){return(a=Number(a))?0<a?1:-1:a};var ea=Object.prototype.hasOwnProperty;function fa(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var e=arguments[d];if(null!=e)for(var f in e)ea.call(e,f)&&(c[f]=e[f])}return c};function ha(a){return Object.keys(a).map(function(b){return a[b]})};function r(a){if(!(this instanceof r))throw new TypeError("Constructor Promise requires `new`");if(!t(a))throw new TypeError("Must pass resolver function");this._state=v;this._value=[];this._isChainEnd=!0;w(this,x(this,y),x(this,z),{then:a})}r.prototype.then=function(a,b){a=t(a)?a:void 0;b=t(b)?b:void 0;if(a||b)this._isChainEnd=!1;return this._state(this._value,a,b)};r.prototype.catch=function(a){return this.then(void 0,a)};
function ia(a){return a===Object(a)&&a instanceof this?a:new this(function(b){b(a)})}function ja(a){return new this(function(b,c){c(a)})}function ka(a){var b=this;return new b(function(c,d){var e=a.length,f=Array(e);if(0===e)return c(f);la(a,function(a,l){b.resolve(a).then(function(a){f[l]=a;0===--e&&c(f)},d)})})}function ma(a){var b=this;return new b(function(c,d){for(var e=0;e<a.length;e++)b.resolve(a[e]).then(c,d)})}
function y(a,b,c,d){if(!b){if(b=d)b=b.promise,b._state=y,b._value=a;return this}d||(d=new A(this.constructor));C(D(d,b,a));return d.promise}function z(a,b,c,d){if(!c)return d&&(b=d.promise,b._state=z,b._value=a),this;d||(d=new A(this.constructor));C(D(d,c,a));return d.promise}function v(a,b,c,d){if(!d){if(!b&&!c)return this;d=new A(this.constructor)}a.push({deferred:d,onFulfilled:b||d.resolve,onRejected:c||d.reject});return d.promise}
function A(a){var b=this;this.promise=new a(function(a,d){b.resolve=a;b.reject=d});return b}function E(a,b,c,d){var e=a._value;a._state=b;a._value=c;d&&b===v&&d._state(c,void 0,void 0,{promise:a,resolve:void 0,reject:void 0});for(var f=0;f<e.length;f++){var h=e[f];a._state(c,h.onFulfilled,h.onRejected,h.deferred)}e.length=0;b===z&&a._isChainEnd&&setTimeout(function(){if(a._isChainEnd)throw c;},0)}function x(a,b){return function(c){E(a,b,c)}}function F(){}
function t(a){return"function"===typeof a}function la(a,b){for(var c=0;c<a.length;c++)b(a[c],c)}function D(a,b,c){var d=a.promise,e=a.resolve,f=a.reject;return function(){try{var a=b(c);w(d,e,f,a,a)}catch(l){f(l)}}}
var C=function(){function a(){for(var a=0;a<d;a++){var b=c[a];c[a]=null;b()}d=0}if("undefined"!==typeof window&&window.postMessage){window.addEventListener("message",a);var b=function(){window.postMessage("macro-task","*")}}else b=function(){setTimeout(a,0)};var c=Array(16),d=0;return function(a){0===d&&b();c[d++]=a}}();
function w(a,b,c,d,e){var f=c,h;try{if(d===a)throw new TypeError("Cannot fulfill promise with itself");var l=d===Object(d);if(l&&d instanceof a.constructor)E(a,d._state,d._value,d);else if(l&&(h=d.then)&&t(h)){var m=function(d){m=f=F;w(a,b,c,d,d)};f=function(a){m=f=F;c(a)};h.call(e,function(a){m(a)},function(a){f(a)})}else b(d)}catch(B){f(B)}};(function(a){a.Math.sign||a.Object.defineProperty(a.Math,"sign",{enumerable:!1,configurable:!0,writable:!0,value:da})})(self);(function(a){a.Object.assign||a.Object.defineProperty(a.Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:fa})})(self);(function(a){a.Object.values||a.Object.defineProperty(a.Object,"values",{configurable:!0,writable:!0,value:ha})})(self);
(function(a){a.Promise||(a.Promise=r,r.default&&(a.Promise=r.default),a.Promise.resolve=ia,a.Promise.reject=ja,a.Promise.all=ka,a.Promise.race=ma)})(self);function na(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function G(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var oa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function H(a){var b=Object.create(null);if(!a)return b;for(var c;c=oa.exec(a);){var d=G(c[1],c[1]),e=c[2]?G(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var I="";
function J(a){var b=a||self;if(b.__AMP_MODE)b=b.__AMP_MODE;else{var c=H(b.location.originalHash||b.location.hash);var d=H(b.location.search);I||(I=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012009252320001");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(c.development)||b.AMP_DEV_MODE),examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"2009252320001",rtvVersion:I};b=b.__AMP_MODE=c}return b}
;var pa=Object.prototype.toString;function qa(a){var b=!1,c=null,d=a;return function(a){for(var e=[],h=0;h<arguments.length;++h)e[h-0]=arguments[h];b||(c=d.apply(self,e),b=!0,d=null);return c}};var K=self.AMP_CONFIG||{},ra=("string"==typeof K.cdnProxyRegex?new RegExp(K.cdnProxyRegex):K.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function sa(a){if(!self.document||!self.document.head||self.location&&ra.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ta={thirdParty:K.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:K.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof K.thirdPartyFrameRegex?new RegExp(K.thirdPartyFrameRegex):K.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:K.cdnUrl||sa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ra,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:K.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:K.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:K.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:K.geoApiUrl||sa("amp-geo-api")};function ua(){}function va(a,b){return b.reduce(function(a,b){return a+"&s[]="+encodeURIComponent(String(wa(b)))},"https://log.amp.dev/?v=012009252320001&id="+encodeURIComponent(a))}
function xa(a,b,c){var d=this,e=c=void 0===c?"":c;this.win=a;this.O=b;this.o=this.win.console&&this.win.console.log&&"0"!=J().log?this.O(parseInt(J().log,10),J().development):0;this.D=e;this.C=null;this.N=qa(function(){a.fetch(ta.cdn+"/rtv/012009252320001/log-messages.simple.json").then(function(a){return a.json()},ua).then(function(a){a&&(d.C=a)})})}
function L(a,b,c,d){if(0!=a.o){var e=a.win.console.log;"ERROR"==c?e=a.win.console.error||e:"INFO"==c?e=a.win.console.info||e:"WARN"==c&&(e=a.win.console.warn||e);c=Array.isArray(d[0])?ya(a,d[0]):d;b="["+b+"]";"string"===typeof c[0]?c[0]=b+" "+c[0]:c.unshift(b);e.apply(a.win.console,c)}}g=xa.prototype;g.isEnabled=function(){return 0!=this.o};g.fine=function(a,b){4<=this.o&&L(this,a,"FINE",Array.prototype.slice.call(arguments,1))};
g.info=function(a,b){3<=this.o&&L(this,a,"INFO",Array.prototype.slice.call(arguments,1))};g.warn=function(a,b){2<=this.o&&L(this,a,"WARN",Array.prototype.slice.call(arguments,1))};g.I=function(a,b){if(1<=this.o)L(this,a,"ERROR",Array.prototype.slice.call(arguments,1));else{var c=M.apply(null,Array.prototype.slice.call(arguments,1));N(this,c);return c}};g.error=function(a,b){var c=this.I.apply(this,arguments);c&&(c.name=a||c.name,self.__AMP_REPORT_ERROR(c))};
g.expectedError=function(a,b){var c=this.I.apply(this,arguments);c&&(c.expected=!0,self.__AMP_REPORT_ERROR(c))};g.createError=function(a){var b=M.apply(null,arguments);N(this,b);return b};g.createExpectedError=function(a){var b=M.apply(null,arguments);N(this,b);b.expected=!0;return b};
g.assert=function(a,b,c){var d;if(Array.isArray(b))return this.assert.apply(this,[a].concat(ya(this,b)));if(!a){var e=(b||"Assertion failed").split("%s"),f=e.shift(),h=f,l=[],m=2;for(""!=f&&l.push(f);0<e.length;){var B=e.shift(),u=arguments[m++];u&&u.tagName&&(d=u);l.push(u);f=B.trim();""!=f&&l.push(f);h+=wa(u)+B}m=Error(h);m.fromAssert=!0;m.associatedElement=d;m.messageArray=l;N(this,m);self.__AMP_REPORT_ERROR(m);throw m;}return a};
g.assertElement=function(a,b){O(this,a,a&&1==a.nodeType,"Element expected",b);return a};g.assertString=function(a,b){O(this,a,"string"==typeof a,"String expected",b);return a};g.assertNumber=function(a,b){O(this,a,"number"==typeof a,"Number expected",b);return a};g.assertArray=function(a,b){O(this,a,Array.isArray(a),"Array expected",b);return a};g.assertBoolean=function(a,b){O(this,a,!!a===a,"Boolean expected",b);return a};
g.assertEnumValue=function(a,b,c){a:{for(var d in a)if(a[d]===b){a=!0;break a}a=!1}if(a)return b;this.assert(!1,'Unknown %s value: "%s"',c||"enum",b)};function N(a,b){b=za(b);a.D?b.message?-1==b.message.indexOf(a.D)&&(b.message+=a.D):b.message=a.D:0<=b.message.indexOf("\u200b\u200b\u200b")&&(b.message=b.message.replace("\u200b\u200b\u200b",""))}function ya(a,b){var c=b.shift();J(a.win).development&&a.N();return a.C&&c in a.C?[a.C[c]].concat(b):["More info at "+va(c,b)]}
function O(a,b,c,d,e){Array.isArray(e)?a.assert(c,e.concat(b)):a.assert(c,(e||d)+": %s",b)}function wa(a){return a&&1==a.nodeType?a.tagName.toLowerCase()+(a.id?"#"+a.id:""):a}function za(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}
function M(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=za(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var P=self.__AMP_LOG,Q=null;function Aa(){if(!Q)throw Error("failed to call initLogConstructor");return new Q(self,function(a,b){return b||1<=a?4:2},"\u200b\u200b\u200b")}
function R(){if(P.dev)return P.dev;if(!Q)throw Error("failed to call initLogConstructor");return P.dev=new Q(self,function(a){return 3<=a?4:2<=a?3:0})};function S(a){return a||{}};var T;function Ba(a,b){var c=Ca();a.addEventListener("message",function(a){try{return b(a)}catch(e){throw self.__AMP_REPORT_ERROR(e),e;}},c?void 0:!1)}function Ca(){if(void 0!==T)return T;T=!1;try{var a={get capture(){T=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return T};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Da(a,b){Ba(a,b)};function Ea(){this.l=null}g=Ea.prototype;g.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};g.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};g.removeAll=function(){this.l&&(this.l.length=0)};g.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};g.getHandlerCount=function(){return this.l?this.l.length:0};function Fa(a,b){this.h=a;this.S=J().rtvVersion||null;this.m=b||null;this.G=null;this.P=1;this.w=Object.create(null);Ga(this)}g=Fa.prototype;g.getData=function(a,b,c){var d=a+"-result",e=this.P++,f=this.registerCallback(d,function(a){a.messageId===e&&(f(),c(a.content))}),h={};h.payload=b;h.messageId=e;this.sendMessage(a,h)};g.makeRequest=function(a,b,c){b=this.registerCallback(b,c);this.sendMessage(a);return b};
g.requestOnce=function(a,b,c){var d=this.registerCallback(b,function(a){d();c(a)});this.sendMessage(a);return d};g.registerCallback=function(a,b){a in this.w||(this.w[a]=new Ea);return this.w[a].add(b)};
g.sendMessage=function(a,b){var c=this.G,d=b,e=this.S;d=void 0===d?{}:d;d.type=a;d.sentinel=c;a="amp-"+((void 0===e?null:e)||"")+JSON.stringify(d);if(this.m)c=this.m,1==c.postMessage.length?Ha(c,a):c.postMessage(a,"*");else for(var f=0,h=this.h;10>f&&h!=this.h.top;f++)c=h=h.parent,e=a,1==c.postMessage.length?Ha(c,e):c.postMessage(e,"*"),f++};function Ha(a,b){a.postMessage(b,S({targetOrigin:"*",includeUserActivation:!0}))}
function Ga(a){Da(a.h,function(b){if(!a.m||b.source==a.m){var c=b.data;if("string"==typeof c&&0==c.indexOf("amp-")&&-1!=c.indexOf("{")){var d=c.indexOf("{");try{var e=JSON.parse(c.substr(d))}catch(f){R().error("MESSAGING","Failed to parse message: "+c,f),e=null}}else e=null;e&&e.sentinel==a.G&&(e.origin=b.origin,a.m||(a.m=b.source),b=e.type,b in a.w&&a.w[b].fire(e))}})}g.setSentinel=function(a){this.G=a};function U(){this.L=100;this.F=this.H=0;this.B=Object.create(null)}U.prototype.has=function(a){return!!this.B[a]};U.prototype.get=function(a){var b=this.B[a];if(b)return b.access=++this.F,b.payload};U.prototype.put=function(a,b){this.has(a)||this.H++;this.B[a]={payload:b,access:this.F};if(!(this.H<=this.L)){R().warn("lru-cache","Trimming LRU cache");a=this.B;b=this.F+1;var c;for(c in a){var d=a[c].access;if(d<b){b=d;var e=c}}void 0!==e&&(delete a[e],this.H--)}};S({c:!0,v:!0,a:!0,ad:!0});var V,Ia;function W(a){this.J();this.h=a;this.K=this.h.name||null;this.tagName=this.startTime=this.sourceUrl=this.sentinel=this.referrer=this.pageViewId=this.mode=this.location=this.initialIntersection=this.initialLayoutRect=this.initialConsentValue=this.initialConsentState=this.hidden=this.domFingerprint=this.data=this.consentSharedData=this.container=this.clientId=this.canonicalUrl=this.canary=this.M=null;this.A=Object.create(null);this.R=0;"[object Object]"===pa.call(this.h.sf_)&&this.h.sf_.cfg?X(this,
this.h.sf_.cfg):this.h.AMP_CONTEXT_DATA?"string"==typeof this.h.AMP_CONTEXT_DATA?this.sentinel=this.h.AMP_CONTEXT_DATA:"[object Object]"===pa.call(this.h.AMP_CONTEXT_DATA)&&X(this,this.h.AMP_CONTEXT_DATA):X(this,this.h.name);var b=this.sentinel.match(/((\d+)-\d+)/);b=Number(b[2]);for(var c=[],d=this.h;d&&d!=d.parent;d=d.parent)c.push(d.parent);this.j=new Fa(a,c[c.length-1-b]);this.j.setSentinel(this.sentinel);Ja(this);Ka(this)}g=W.prototype;g.J=function(){};
function Ja(a){a.j.makeRequest("send-embed-state","embed-state",function(b){a.hidden=b.pageHidden;b=a.h.document.createEvent("Event");b.data={hidden:a.hidden};b.initEvent("amp:visibilitychange",!0,!0);a.h.dispatchEvent(b)})}g.onPageVisibilityChange=function(a){return this.j.registerCallback("embed-state",function(b){a({hidden:b.pageHidden})})};g.observeIntersection=function(a){return this.j.makeRequest("send-intersections","intersection",function(b){a(b.changes)})};
g.getHtml=function(a,b,c){this.j.getData("get-html",S({selector:a,attributes:b}),c)};g.getConsentState=function(a){this.j.getData("get-consent-state",null,a)};g.requestResize=function(a,b,c){var d=this.R++;this.j.sendMessage("embed-size",S({id:d,width:a,height:b,hasOverflow:c}));a=new na;this.A[d]=a;return a.promise};
function Ka(a){a.j.registerCallback("embed-size-changed",function(b){b=b.id;void 0!==b&&(a.A[b].resolve(),delete a.A[b])});a.j.registerCallback("embed-size-denied",function(b){b=b.id;void 0!==b&&(a.A[b].reject("Resizing is denied"),delete a.A[b])})}function La(a,b){a.j.sendMessage("user-error-in-iframe",S({message:b+" is deprecated",expected:!0}))}g.onResizeSuccess=function(a){this.j.registerCallback("embed-size-changed",function(b){a(b.requestedHeight,b.requestedWidth)});La(this,"onResizeSuccess")};
g.onResizeDenied=function(a){this.j.registerCallback("embed-size-denied",function(b){a(b.requestedHeight,b.requestedWidth)});La(this,"onResizeDenied")};g.signalInteractive=function(){this.j.sendMessage("signal-interactive")};g.addContextToIframe=function(a){a.name=this.K};g.noContentAvailable=function(){this.j.sendMessage("no-content")};
function X(a,b){if("string"===typeof b)try{var c=JSON.parse(b)}catch(l){c=null}else c=b;var d=c;b=d._context||d.attributes._context;a.data=d.attributes||d;"_context"in a.data&&delete a.data._context;a.canary=b.canary;a.canonicalUrl=b.canonicalUrl;a.clientId=b.clientId;a.consentSharedData=b.consentSharedData;a.container=b.container;a.domFingerprint=b.domFingerprint;a.hidden=b.hidden;a.initialConsentState=b.initialConsentState;a.initialConsentValue=b.initialConsentValue;a.initialLayoutRect=b.initialLayoutRect;
a.initialIntersection=b.initialIntersection;c=b.location.href;V||(V=self.document.createElement("a"),Ia=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new U));var e=Ia,f=V;if(e&&e.has(c))c=e.get(c);else{f.href=c;f.protocol||(f.href=f.href);var h={href:f.href,protocol:f.protocol,host:f.host,hostname:f.hostname,port:"0"==f.port?"":f.port,pathname:f.pathname,search:f.search,hash:f.hash,origin:null};"/"!==h.pathname[0]&&(h.pathname="/"+h.pathname);if("http:"==h.protocol&&80==h.port||"https:"==h.protocol&&
443==h.port)h.port="",h.host=h.hostname;h.origin=f.origin&&"null"!=f.origin?f.origin:"data:"!=h.protocol&&h.host?h.protocol+"//"+h.host:h.href;e&&e.put(c,h);c=h}a.location=c;a.mode=b.mode;a.pageViewId=b.pageViewId;a.referrer=b.referrer;a.sentinel=b.sentinel;a.sourceUrl=b.sourceUrl;a.startTime=b.startTime;a.tagName=b.tagName;a.M=d.type||null}g.report3pError=function(a){a.message&&this.j.sendMessage("user-error-in-iframe",S({message:a.message}))};function Y(){W.apply(this,arguments)}Y.prototype=aa(W.prototype);
Y.prototype.constructor=Y;if(q)q(Y,W);else for(var Z in W)if("prototype"!=Z)if(Object.defineProperties){var Ma=Object.getOwnPropertyDescriptor(W,Z);Ma&&Object.defineProperty(Y,Z,Ma)}else Y[Z]=W[Z];Y.T=W.prototype;Y.prototype.J=function(){};(function(){Q=xa;R();P.user||(P.user=Aa())})();(function(a){self.__AMP_REPORT_ERROR=a})(function(){});try{var windowContextCreated=new Event("amp-windowContextCreated");window.context=new Y(window);window.dispatchEvent(windowContextCreated)}catch(a){};})();

//# sourceMappingURL=ampcontext-v0.js.map
